### ISSUE TITLE
Tabs issue in Modern Aqua theme SugarCRM

### ISSUE THREAD

**Issue by ravinduworks** [cognitom/ModernAqua-Theme-for-SugarCRM#3]
Hi, 

I have installed Modern Aqua successfully on Sugarcrm 6.3.0.

Here are the issue I found:
1. sitemap tab on the right top corner is not functioning at all. 
2. Last Viewed option is not displaying the last viewed items.

Please help me in fixing this issue.

---

Ravi

**Comment by ernierasta** [comment]
Hi!
Thanx for bug report. It should be fixed now.

**Comment by ravinduworks** [comment]
Hi, 

I found 'sitemap' is working fine. But 'last viewed' list is still not showing, Could you please check it?

**Comment by ernierasta** [comment]
Hmm,
and when you open f.e. client or contact detail view - nothing?  I just cloned fresh copy to my testing server - it looks ok for me.
